name: Feedback
description: Feedback issue template
labels: ["feedback"]
body:
  - type: dropdown
    attributes:
      label: 问题类型 Issue type Issueタイプ
      options:
        - Bug反馈 Bug report Bug報告
        - 建议 Suggestion 提案
    validations:
      required: true
  - type: input
    attributes:
      label: 操作系统 Operating System OS
      description: |
        输入您的操作系统名称。
        The operating system you are using.
        ご使用のOSを入力してください。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 详细说明 Details 詳細
      description: |
        详细说明您遇到的问题或建议。
        Describe your issue or suggestion.
        あなたの問題や提案を説明してください。
    validations:
      required: true
