name: Feedback
description: Feedback issue template
title: 'Title 标题'
labels: ["feedback"]
body:
  - type: dropdown
    attributes:
      label: Issue type 问题类型
      options:
        - Bug report Bug反馈
        - Suggestion 建议
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System 操作系统
      description: |
        The operating system you are using.
        输入您的操作系统名称。
    validations:
      required: true
  - type: textarea
    attributes:
      label: Details 详细说明
      description: |
        Describe your issue or suggestion.
        详细说明您遇到的问题或建议。
    validations:
      required: true
