name: Issue
description: Issue template
body:
  - type: dropdown
    attributes:
      label: Issue type
      options:
        - Bug report
        - Suggestion
        - Other
    validations:
      required: true
  - type: dropdown
    id: store
    attributes:
      label: Download source
      options:
        - Microsoft Store
        - Steam
        - Google Play
        - App Store
        - Other
    validations:
      required: true
  - type: input
    attributes:
      label: If other, please specify
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Operating System
      description: The operating system and version you are using.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Details
      description: Describe your issue or suggestion.
    validations:
      required: true
